[".zsh/git-prompt"]
    type = "git-repo"
    url = "https://github.com/woefe/git-prompt.zsh"
[".zsh/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
